### ISSUE TITLE
Can you open source your lora model or dataset?

### ISSUE THREAD

**Issue by StudyingLover** [Coldwave96/llama-honeypot#1]
I think this is a very good project. I use llama2 as my backend model, but the effect of my direct promt is not ideal. Can you open source your model or training data?

**Comment by Coldwave96** [comment]
> I think this is a very good project. I use llama2 as my backend model, but the effect of my direct promt is not ideal. Can you open source your model or training data?

The training dataset is gathered by the company through real world systems or honeypots. By far, I'm not allowed to opensource either the training data or the adapter due to some privacy issues.

Maybe you could do similar works. Gather raw datasets by deploying multiple honeypots or simulating raw data via some linux running libraries.
